DROP TABLE IF EXISTS user_local;
DROP TABLE IF EXISTS user_facebook;
DROP TABLE IF EXISTS user_twitter;

CREATE TABLE IF NOT EXISTS user_local (
	user_id INTEGER PRIMARY KEY AUTOINCREMENT,
	email STRING UNIQUE NOT NULL,
	name STRING NOT NULL,
	pwd_hash STRING NOT NULL
);

CREATE TABLE IF NOT EXISTS user_facebook (
	user_id STRING PRIMARY KEY NOT NULL,
	email STRING NOT NULL,
	name STRING NOT NULL
);

CREATE TABLE IF NOT EXISTS user_twitter (
	user_id STRING PRIMARY KEY NOT NULL,
	email STRING NOT NULL,
	name STRING NOT NULL
);
