DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS user_email;
DROP TABLE IF EXISTS user_facebook;
DROP TABLE IF EXISTS user_twitter;

CREATE TABLE IF NOT EXISTS user (
	user_id INTEGER PRIMARY KEY AUTOINCREMENT,
	name STRING NOT NULL,
	pwd_hash STRING
);

CREATE TABLE IF NOT EXISTS user_email (
	email STRING PRIMARY KEY,
	user_id INTEGER UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS user_facebook (
	facebook_id STRING PRIMARY KEY,
	user_id INTEGER UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS user_twitter (
	twitter_id STRING PRIMARY KEY,
	user_id INTEGER UNIQUE NOT NULL
);
